/** Fila de imagens com processamento paralelo, cache persistente e prioridade por código. */
import { useCallback, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { buscarImagemPorEan, buscarImagemPorNome, urlDeImagemValida } from "@/modules/imagens/busca-imagens";
import { buscarCandidatosGoogle } from "@/lib/google-imagens.functions";
import { pontuarCandidato, type Pontuacao } from "@/modules/imagens/confianca-google";

const LOTE = 12;
const PAGINA = 500;
const TODAS_CATEGORIAS = "__all__";
const SEM_CATEGORIA = "__uncategorized__";
const STORAGE_KEY = "nodus:image-search-state:v2";
type ImageStatus = "pending" | "found" | "not_found" | "pending_approval" | "rejected" | "manual";
type ImageSearchState = { status: Exclude<ImageStatus, "pending" | "found" | "manual">; checkedAt: string; fingerprint: string };
export interface ProdutoSemImagem { id: string; ean: string | null; description: string; category: string | null; image_status: ImageStatus; image_search_version: number; }
export interface CandidatoGoogle { id: string; produto: ProdutoSemImagem; url: string; titulo: string; pontuacao: Pontuacao; }
function fingerprint(p: Pick<ProdutoSemImagem,"id"|"ean"|"description">) { return `${p.id}|${p.ean ?? ""}|${p.description.trim().toUpperCase()}`; }
function lerEstados(): Record<string, ImageSearchState> { if (typeof window === "undefined") return {}; try { return JSON.parse(localStorage.getItem(STORAGE_KEY) ?? "{}") as Record<string, ImageSearchState>; } catch { return {}; } }
function gravarEstados(e: Record<string, ImageSearchState>) { if (typeof window !== "undefined") localStorage.setItem(STORAGE_KEY, JSON.stringify(e)); }
function salvarEstado(p: ProdutoSemImagem,s: ImageSearchState["status"]) { const e=lerEstados(); e[p.id]={status:s,checkedAt:new Date().toISOString(),fingerprint:fingerprint(p)}; gravarEstados(e); }
async function carregarPendentes(categoria:string):Promise<ProdutoSemImagem[]> { const produtos:ProdutoSemImagem[]=[]; let inicio=0; while(true){ let q=supabase.from("products").select("id, ean, description, category, image_url").is("image_url",null).order("description").range(inicio,inicio+PAGINA-1); if(categoria===SEM_CATEGORIA) q=q.is("category",null); else if(categoria!==TODAS_CATEGORIAS) q=q.eq("category",categoria); const {data,error}=await q; if(error)throw error; const pagina=(data??[]) as Array<Omit<ProdutoSemImagem,"image_status"|"image_search_version"> & {image_url:string|null}>; const estados=lerEstados(); for(const p of pagina){const estado=estados[p.id]; if(!estado||estado.fingerprint!==fingerprint(p)) produtos.push({...p,image_status:"pending",image_search_version:1});} if(pagina.length<PAGINA)break; inicio+=PAGINA;} return produtos; }
function prioridade(p:ProdutoSemImagem){ if(p.ean?.trim())return 0; if(p.description.split(/\s+/).filter(Boolean).length>=3)return 1; return 2; }
export function useImagensPendentes(categoria=TODAS_CATEGORIAS){ const queryClient=useQueryClient(); const[rodando,setRodando]=useState(false); const[processados,setProcessados]=useState(0); const[encontrados,setEncontrados]=useState(0); const[semResultado,setSemResultado]=useState(0); const[candidatos,setCandidatos]=useState<CandidatoGoogle[]>([]); const[versaoFila,setVersaoFila]=useState(0); const pendentes=useQuery({queryKey:["imagens-pendentes",categoria,versaoFila],queryFn:()=>carregarPendentes(categoria)}); const lista=pendentes.data??[];
 const atualizarEstado=useCallback(async(p:ProdutoSemImagem,s:ImageSearchState["status"])=>salvarEstado(p,s),[]); const salvarImagem=useCallback(async(id:string,url:string)=>{const{error}=await supabase.from("products").update({image_url:url}).eq("id",id);if(error)throw error;},[]);
 const completar=useCallback(async()=>{if(rodando||!lista.length)return;setRodando(true);setProcessados(0);setEncontrados(0);setSemResultado(0);const fila=[...lista].sort((a,b)=>prioridade(a)-prioridade(b));let indice=0; const trabalhador=async()=>{while(indice<fila.length){const p=fila[indice++]!;try{const url=p.ean?await buscarImagemPorEan(p.ean):await buscarImagemPorNome(p.description);if(url){await salvarImagem(p.id,url);const e=lerEstados();delete e[p.id];gravarEstados(e);setEncontrados(v=>v+1);}else{const{candidatos:achados}=await buscarCandidatosGoogle({data:{termo:p.description}});const validados:CandidatoGoogle[]=[];for(const a of achados.slice(0,8)){if(!(await urlDeImagemValida(a.url)))continue;validados.push({id:`${p.id}-${a.url}`,produto:p,url:a.url,titulo:a.titulo,pontuacao:pontuarCandidato(a,p)});if(validados.length>=3)break;}if(validados.length){validados.sort((a,b)=>b.pontuacao.total-a.pontuacao.total);await atualizarEstado(p,"pending_approval");setCandidatos(v=>[...v.filter(x=>x.produto.id!==p.id),...validados]);}else{await atualizarEstado(p,"not_found");setSemResultado(v=>v+1);}}}catch(erro){console.error("Falha ao buscar imagem",p.id,erro);await atualizarEstado(p,"not_found");setSemResultado(v=>v+1);}setProcessados(v=>v+1);}}; await Promise.all(Array.from({length:Math.min(LOTE,fila.length)},trabalhador));setRodando(false);setVersaoFila(v=>v+1);queryClient.invalidateQueries({queryKey:["products"]});queryClient.invalidateQueries({queryKey:["dashboard-stats"]});toast.success(`Busca concluída: ${fila.length} produto(s) processado(s).`);},[lista,queryClient,rodando,salvarImagem,atualizarEstado]);
 const pesquisarNovamente=useCallback(()=>{gravarEstados({});setCandidatos([]);setVersaoFila(v=>v+1);toast.success("Histórico de buscas limpo. Os produtos sem imagem podem ser pesquisados novamente.");},[]);
 const aprovar=useCallback(async(c:CandidatoGoogle)=>{try{await salvarImagem(c.produto.id,c.url);const e=lerEstados();delete e[c.produto.id];gravarEstados(e);setCandidatos(v=>v.filter(x=>x.produto.id!==c.produto.id));setVersaoFila(v=>v+1);queryClient.invalidateQueries({queryKey:["products"]});toast.success("Imagem aprovada e salva.");}catch(erro){toast.error(erro instanceof Error?erro.message:"Não foi possível salvar a imagem");}},[queryClient,salvarImagem]);
 const rejeitar=useCallback(async(c:CandidatoGoogle)=>{try{await atualizarEstado(c.produto,"rejected");setCandidatos(v=>v.filter(x=>x.produto.id!==c.produto.id));setVersaoFila(v=>v+1);toast.success("Candidato rejeitado. O produto não será pesquisado novamente automaticamente.");}catch(erro){toast.error(erro instanceof Error?erro.message:"Não foi possível registrar a rejeição");}},[atualizarEstado]);
 return{lista,carregando:pendentes.isLoading,rodando,processados,encontrados,semResultado,candidatos,totalSemImagem:lista.length,aguardandoAprovacao:new Set(candidatos.map(x=>x.produto.id)).size,completar,pesquisarNovamente,aprovar,rejeitar}; }
